# Generated by Django 5.2.8 on 2025-11-30 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'managed': False, 'ordering': ['apellido', 'nombre'], 'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'managed': False, 'ordering': ['nombre_materia'], 'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'managed': False, 'ordering': ['apellido', 'nombre'], 'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
        migrations.AlterModelOptions(
            name='resena',
            options={'managed': False, 'ordering': ['-fecha'], 'verbose_name': 'Reseña', 'verbose_name_plural': 'Reseñas'},
        ),
        migrations.AlterModelOptions(
            name='reservaclase',
            options={'managed': False, 'ordering': ['-fecha_reserva'], 'verbose_name': 'Reserva de Clase', 'verbose_name_plural': 'Reservas de Clases'},
        ),
    ]
